name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y build-essential meson nasm libfreetype6-dev libfribidi-dev libharfbuzz-dev libfontconfig-dev liblcms2-dev libarchive-dev librubberband-dev libuchardet-dev libxfixes-dev libzimg-dev

      - name: Cache build directories
        uses: actions/cache@v4
        with:
          path: |
            ffmpeg
            fribidi
            libass
            libplacebo
            mpv
            build_libs
            ffmpeg_build
          key: mpv-build-${{ github.run_id }}
          restore-keys: |
            mpv-build-

      - name: Build
        run: |
          ./rebuild -j$(nproc)
          mkdir dist
          DESTDIR="$(pwd)/dist" ./install

      - uses: actions/upload-artifact@v7
        with:
          name: mpv-build
          path: dist/usr/local
  
  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: mpv-build
          path: mpv-build

      - name: Prepare artifacts
        run: tar -czvf mpv-build.tar.gz mpv-build/*
      
      - name: Create git tag
        id: create-git-tag
        run: |
          tag="autobuild-$(date -u '+%Y-%m-%d-%H-%M')"
          echo "TAG=$tag" >> $GITHUB_OUTPUT

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.create-git-tag.outputs.TAG }}"
          prerelease: false
          title: "${{ steps.create-git-tag.outputs.TAG }}"
          files: mpv-build.tar.gz
