name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y build-essential meson nasm libfreetype6-dev libfribidi-dev libharfbuzz-dev libfontconfig-dev

      - name: Build
        run: |
          ./rebuild -j$(nproc)
          mkdir dist
          DESTDIR="$(pwd)/dist" ./install

      - uses: actions/upload-artifact@v7
        with:
          name: mpv-build
          path: dist/usr/local
